name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master    

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=arfiya-shikalgar
            -Dsonar.projectKey=arfiya-shikalgar_secure-pipeline-demo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
dast-owasp-zap:
  name: DAST - OWASP ZAP Scan
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: "https://example.com"